[workspace]
members = [
    #
    "biocore",
    "ensembl",
    "genomes1000",
    "gwas_catalog",
    "hail",
    "ids",
    "liftover",
    "pan_ukbb",
    "pgs_catalog",
    "primeedit",
    "puv", "resource",
    "utile",
]
exclude = ["target"]
resolver = "2"
