[toolchain]
channel = "nightly-2026-01-30"
targets = ["wasm32-unknown-unknown"]
components = [
    "rustc",
    "cargo",
    "rustfmt",
    "rust-std",
    "rust-docs",
    "rust-analyzer",
    "clippy",
    "miri",
    "rust-src",
    # "rust-mingw",
    # "llvm-tools",
    # "rustc-dev",
]
